version: "3"
services:
  app:
    build: .
    image: 255537051466.dkr.ecr.eu-west-3.amazonaws.com/qranalyzer:linux-3
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - RDS_HOSTNAME=mysql
      - RDS_DB_NAME=qranalyzer
      - RDS_USERNAME=root
      - RDS_PASSWORD=secret
      - RDS_PORT=3306
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

volumes:
  mysql:
